pipelines:
  default:
    - step:
        name: Build and run tests for PHP 5.6
        image: php:5.6-cli
        script:
            - apt-get update && apt-get install -y libevent-dev libssl-dev
            - phpize
            - ./configure --with-event-core --with-event-extra --with-event-openssl
            - make test
    - step:
        name: Build and run tests for PHP 7.1
        image: php:7.1-cli
        script:
            - apt-get update && apt-get install -y libevent-dev libssl-dev
            - phpize
            - ./configure --with-event-core --with-event-extra --with-event-openssl
            - make test